### ISSUE TITLE
Feedback - Saving issue

### ISSUE THREAD

**Issue by NVieregg** [LAYAIraq/LAYA-Iraq-Frontend#292]
Two saving issues occur and I can't find the error :(
1. The course feedback block does not always get saved to the course and disappears when the course is loaded by another user than the author.
2. The course feedback is not saved anymore since Enrollment was added. 

Error logs (Firefox and Chromium):

![firefox-error](https://user-images.githubusercontent.com/97884768/187154398-5ffdcd52-fc01-4e57-977a-f2ace197e687.png)
![chromium-error](https://user-images.githubusercontent.com/97884768/187154412-d3624c7c-558e-41d9-a730-97373f99d6df.png)

**Comment by cmauf** [comment]
@NVieregg please close if no longer relevant
